language: python
env:
  global:
    - secure: "NvCrVJZvij+4bhyFsOQdSGRbAxgLShsGdCyA3UMQLCpni2vnEqpL6p4n06Nv/RYwd8hakADTMaMZIXdeSCmT5pBO3irzXOMWyknD70g0DYvDBXPKfts2S2u0D2xg25sQxJuX8FtMNkGnXcocg/XFUqocAoi39KExmsSbA1BeSytiibne4VgenUtojfCNZv7r/u+qPW4h+HqJVx0iZMB8V1AkGwtnL7ZvR5oU/91LsjqiQoFw548TDgzgLxTtOkLO41jiDHXkHsoZUNPNorAXB/PVIzGEvs9V3rohTr+BheQLbrn4J3Sm7mKayvBWJxd2gjqW+FSv+82+LzRRf+psJUO9ILzeIp2pFuzh06FkoVb5T2bNQzqqRQfPxLLr3tLC5pZhhQhZDzYvokouFnUAHjJt7/wWAqiv3lFmHJM0hSmXR9RTaGEcXcXamTf8E44FwziVb6T21U0r9GAPQgSXSCBNkd7uGaOmD5V9NIk+X+JDdt/eryDggN2HHwmx7fKHVOUW2eBb4cj78zMSLcqZDLSjlQ/3sgOXrXIIK28TFvyBd1KZ6rF2VKktMYqYsfLIGG+a+NspNAhQ86Gxasl8Fl1/KlpHXS6OgUrZtQb9ZHQ1gko0wJBvkKh058mSXQcVge3o2DJ9OwRFUJ7yULRaSW/DOQ3Rf6Bp0LF45QSYDxw="
    - secure: "2c12VQvtRy4VJ8pyc/XgJQcjkv3F6YynjZu96GZE0/PfCQaWSbuw7/JZ/nsCMRMa/WxCy1gJsjmxbBzWGlEAHgSt4LMSYDDYq0fhD7ZFwsB7iHnCIX/PlSSChz1l3VfBqxvRs5wjAVAoci7+yOdNFGFWbR4/s6BBSDMHtsp8i+WRfDFyngNF31LrTsk9t8Lmh6jO326Tx6DcRRupo0i9PTWvrlTv43ttOO0+ei8TNnaFQh6BlHD85KblvG0LwRMs81oBVauEmhvS/uRsThHzLMEVQkAMe0KKbdPS8A0TRJ1LMLZmQmrXK1ZtK4eSWWrmlnZtrxWJ6xSuQ3Y96spQ4qgLk1TEiDegdsusIQsI1Nkwwo0SwpsmItI2EeKsOKE8hhpiJRUI9ZPn72K922IMxt6biLtG+e+FEJsiAkQBheb8PX70uAAEbA5DC+b9AbrtRrd+I3V2G4xW1QRqIMbuDnFmFqLmaZ4Qn6y9v2+J6oSgDB00LZQbaoTDO+wC1X3x+wVu70qXaoDm6fnhDy3H68YTJr5VIBuAKVzTGVQJ4BbSEilSK1KRVjN5MudFmx6PfOuCjm0VhdN3W6L9TXMFv1CzobJWkpeqSAIuIrDxG+I0B5wr+d4r0attYm+Kx++l59FEIVM6xQ2Q2XxQJCUSL3jsbjo3eJNzPXqJuQHCykU="
python:
- '3.4'
- '3.5'
install:
- python setup.py install
script:
- python tests.py
 

